name: CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simulate Deployment
        run: echo "Deploying app to staging server..."

      - name: Use Secret Key
        run: echo "Using deploy key: ${{ secrets.DEPLOY_KEY }}"
